language: java
jdk:
  - openjdk11

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -mugoloka@gmail.com
    on_success: never # default: change
    on_failure: always # defa,ult: always
    env:
      global:
         - CODECOV_TOKEN="eb49c245-7b48-4808-bd22-e61a13eff263"
